### ISSUE TITLE
Translations helper

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/web-tools#3]
After bedita/bedita#1494 we may obtain an object translation in a single object/list GET response. 

A new helper like `TrHelper` (?) or  `I18nHelper` (?) should provide:

* a method to obtain an object field in a given language (if available in the response)
* a method to check if an object has a translation of a field in a given language

**Comment by batopa** [comment]
Maybe it's better `TrHelper` since `I18nHelper` is also in the PR https://github.com/bedita/i18n/pull/3

**Comment by stefanorosanelli** [comment]
Or may we could use `I18nHelper` directly instead and move these new helper methods to `bedita/i18n` - makes sense right now...

**Comment by batopa** [comment]
Yes, maybe it's better

**Comment by didoda** [comment]
So... is it not anymore a web-tools issue?
I don't know... I'd rather stay simple, with a 2 methods `TrHelper` in web-tools (); then, when PR bedita/i18n#3 is merged, we could refactor and move logic to bedita core.

**Comment by didoda** [comment]
Issue is obsolete
